runtime: python39
instance_class: F4_1G

includes:
  - env_variables.yaml

handlers:
- url: /favicon\.ico
  static_files: static/images/favicon.ico
  upload: static/images/favicon.ico

- url: /static
  static_dir: static
 
- url: /.*
  script: auto
